import {onCall, HttpsError} from "firebase-functions/v2/https";
import {defineSecret} from "firebase-functions/params";
import * as admin from "firebase-admin";
import {google} from "googleapis";

const GOOGLE_CLIENT_ID = defineSecret("GOOGLE_CLIENT_ID");
const GOOGLE_CLIENT_SECRET = defineSecret("GOOGLE_CLIENT_SECRET");
const GOOGLE_REDIRECT_URI = defineSecret("GOOGLE_REDIRECT_URI");

export const syncToGoogleClassroom = onCall(
  {
    region: "us-central1",
    memory: "512MiB",
    secrets: [
      GOOGLE_CLIENT_ID,
      GOOGLE_CLIENT_SECRET,
      GOOGLE_REDIRECT_URI,
    ],
  },
  async (request) => {
    if (!request.auth) {
      throw new HttpsError("unauthenticated", "You must be logged in.");
    }

    const {orgId, courseId, quiz} = request.data;

    if (!orgId || !quiz) {
      throw new HttpsError("invalid-argument", "Missing orgId or quiz data.");
    }

    // 1. Get stored tokens from Firestore
    const integrationDoc = await admin
      .firestore()
      .collection("orgs")
      .doc(orgId)
      .collection("members")
      .doc(request.auth.uid)
      .collection("integrations")
      .doc("google")
      .get();

    if (!integrationDoc.exists) {
      throw new HttpsError(
        "failed-precondition",
        "Google account not connected. Please connect Google in Settings first."
      );
    }

    const integration = integrationDoc.data();

    if (!integration) {
      throw new HttpsError(
        "failed-precondition",
        "Google account not connected. Please connect Google in Settings first."
      );
    }

    // 2. Set up OAuth client with stored tokens
    const oauth2Client = new google.auth.OAuth2(
      GOOGLE_CLIENT_ID.value(),
      GOOGLE_CLIENT_SECRET.value(),
      GOOGLE_REDIRECT_URI.value()
    );

    oauth2Client.setCredentials({
      access_token: integration.accessToken,
      refresh_token: integration.refreshToken,
      expiry_date: integration.expiryDate,
    });

    // 3. Auto-save refreshed tokens back to Firestore
    oauth2Client.on("tokens", async (newTokens) => {
      await integrationDoc.ref.update({
        accessToken: newTokens.access_token ?? integration.accessToken,
        refreshToken: newTokens.refresh_token ?? integration.refreshToken,
        expiryDate: newTokens.expiry_date ?? integration.expiryDate,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
    });

    const classroom = google.classroom({version: "v1", auth: oauth2Client});

    // 4. If no courseId passed, return list of courses for user to pick
    if (!courseId) {
      const coursesResponse = await classroom.courses.list({
        courseStates: ["ACTIVE"],
      });

      const courses = (coursesResponse.data.courses ?? []).map((c) => ({
        id: c.id,
        name: c.name,
        section: c.section ?? "",
      }));

      return {requiresCourseSelection: true, courses};
    }

    // 5. Create the Classroom assignment with the Form attached
    const courseWorkResponse = await classroom.courses.courseWork.create({
      courseId,
      requestBody: {
        title: quiz.title,
        description: quiz.description || "Generated by Asseska",
        workType: "ASSIGNMENT",
        state: "PUBLISHED",
        maxPoints: quiz.maxPoints ?? 100,
        materials: [
          {
            link: {
              url: quiz.formUrl,
              title: `${quiz.title} — Answer Form`,
            },
          },
        ],
      },
    });

    // 6. Save the courseWorkId on the quiz in Firestore for grade sync later
    await admin
      .firestore()
      .collection("orgs")
      .doc(orgId)
      .collection(admin.firestore().collection("templates").path)
      // adjust to your actual quiz collection path
      .doc(quiz.id)
      .update({
        classroomCourseId: courseId,
        classroomCourseWorkId: courseWorkResponse.data.id,
        classroomSyncedAt: admin.firestore.FieldValue.serverTimestamp(),
      });

    return {
      success: true,
      classroomUrl: courseWorkResponse.data.alternateLink,
      courseWorkId: courseWorkResponse.data.id,
    };
  }
);
